### ISSUE TITLE
CA cert added twice to fullchain cert

### ISSUE THREAD

**Issue by dpisano** [bzed/bzed-letsencrypt#13]
I was looking at my `example.com_fullchain.pem` on my client and it looks like the CA cert is is there twice. On my puppet master `example.com.crt` only has the CA in there once. I'm guessing what is happening is that `letsencrypt.sh` is putting the CA cert in `example.com.crt` and `letsencrypt_get_certificate_chain.sh` is adding it again to `example.com_fullchain.pem`. Is this intentional or just an oversight?

**Comment by bzed** [comment]
Unfortunately I can't reproduce your issue here. You'll have to debug this I'm afraid.

**Comment by dpisano** [comment]
I think that it might have been fixed by lukas2511/letsencrypt.sh@d81eb58536e3ae1170de3eda305688ae28d0575b. The certs that I'm looking at are from the end of July. I will need to check the next time a get a cert or when one of my current ones renew.

**Comment by dpisano** [comment]
It looks like it was fixed by that commit. I just requested a new cert and the CA cert is only in there once.
