### ISSUE TITLE
Support for adding to dehydrated config

### ISSUE THREAD

**Issue by rmb938** [bzed/bzed-letsencrypt#16]
If I want to use a hook that has config options (https://github.com/kappataumu/letsencrypt-cloudflare-hook) I need to be able to add options to the config file.

**Comment by bzed** [comment]
As far as I understand the hook you've linked, it is possible to pass the options via the environment. the hook_env parameter will be passed into the environment of the exec call which runs dehydrated, so adding these options there should work. The other option is to use a wrapper around your hook as hook, which exports the necessary options.

**Comment by bzed** [comment]
Also see #30 and #31
