### ISSUE TITLE
Clearer doc about how it works

### ISSUE THREAD

**Issue by siliconalchemy** [bzed/bzed-letsencrypt#18]
README could explain how the module works a bit more.  It's not clear or obvious that it depends on both the 'client' nodes and the puppetmasters to be running puppet in daemon mode as the CSR/signing/deploy mechanism happens in multiple stages/puppet runs.  Lots of people run puppet in agent or oneshot mode and in this case this modules workflow isn't obvious and doesn't look like it's working.
But it's great when you work that out :)

**Comment by bzed** [comment]
If you have some suggestions for better wordings - I'll happily accept pull requests :smile:

**Comment by bzed** [comment]
Please use https://github.com/bzed/bzed-dehydrated/ - it is also slowly being documented and comes with a reference documentation and all fancy new puppet stuff. Just needs more time for more documentation.
