### ISSUE TITLE
/etc/letsencrypt hierarchy/organisation

### ISSUE THREAD

**Issue by siliconalchemy** [bzed/bzed-letsencrypt#19]
If there are lots of domains to sign, /etc/letsencrypt will get quite messy as there is no per-domain hierarchy.  Would be nice to either split each certs/csr/private directory further by domain, or else have a domain directory within /etc/letsencrypt and then have separate certs/csr/private within the domain directory.

**Comment by bzed** [comment]
I did not implement this in https://github.com/bzed/bzed-dehydrated/ - right now you have three directories with one or a few files per domain. I can't see that having a directory per domain with files inside makes a useful difference. Also most other tools (like the pki / nssdb) work like this. So.. wontfix, sorry :)
