### ISSUE TITLE
/etc/letsencrypt path hardcoded

### ISSUE THREAD

**Issue by siliconalchemy** [bzed/bzed-letsencrypt#21]
/etc/letsencrypt path is hardcoded in:
 lib/facter/letsencrypyt_csr.rb
 spec/classes/letsencrypt_init_spec.rb

**Comment by bzed** [comment]
Can't see the problem here - its hardcoded in other places, too. And not hardcoding it into a facter module will produce more issues than it will help.

**Comment by siliconalchemy** [comment]
It would be nice to have the path configurable if possible.  Some people prefer to keep certs in /var or /srv or some part of the filesystem that is shared/replicated - /etc is generally a local dir.

**Comment by bzed** [comment]
Yeah, I understand the problem - but right now I can't see a way to fix that.

**Comment by bzed** [comment]
@siliconalchemy thats possible in bzed-dehydrated now. bzed-letsencrypt is deprecated with today.

**Comment by siliconalchemy** [comment]
@bzed That's great, I'll migrate over to the new project.  Thanks :)
