### ISSUE TITLE
Duplicate resource errors

### ISSUE THREAD

**Issue by siliconalchemy** [bzed/bzed-letsencrypt#26]
If you request the same certificate from multiple nodes then you get an error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: A duplicate resource was found while collecting exported resources, with the type and title Letsencrypt::Request[test3.example.net] on node infra
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

```
puppet node exports
Name                                      Exports                                 
dev1.example.net    Letsencrypt::request[test.example.net]
dev2.example.net    Letsencrypt::request[test.example.net]
```

**Comment by bzed** [comment]
Are you trying to get the same certificate for two hosts?  That's broken I'm afraid 😣

Am 4. Dezember 2016 08:42:42 MEZ, schrieb siliconalchemy <notifications@github.com>:
>If you request the same certificate from multiple nodes then you get an
>error:
>```
>Error: Could not retrieve catalog from remote server: Error 500 on
>SERVER: Server Error: A duplicate resource was found while collecting
>exported resources, with the type and title
>Letsencrypt::Request[test3.example.net] on node infra
>Warning: Not using cache on failed catalog
>Error: Could not retrieve catalog; skipping run
>```
>
>```
>puppet node exports
>Name                                      Exports                      
>          
>dev1.example.net    Letsencrypt::request[test.example.net]
>dev2.example.net    Letsencrypt::request[test.example.net]
>```
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bzed/bzed-letsencrypt/issues/26

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by bzed** [comment]
To be able to handle this at least the following things are needed:

- The requesting host needs to be listed in the ;etsencryt::request $name
- There needs to be one folder per node on the puppetmaster, not only one folder per requested domain
- A sane migration for that is needed, although I want to rename the module to dehydrated anyway - so the migration part could go into the "old" letsencrypt module which is a wrapper around the new one....

The other option would be to add an option where the puppetmaster also generated the private key and ships it to all hosts where the certificate is being requested. But I don't want to have that as default.

**Comment by bzed** [comment]
Please use https://github.com/bzed/bzed-dehydrated/ - it solves this issue and many others.
