### ISSUE TITLE
letsencrypt user/group random uid/gid

### ISSUE THREAD

**Issue by siliconalchemy** [bzed/bzed-letsencrypt#28]
The letsencrypt group is defined in setup.pp, the user defined in request/handler.pp.  Neither have the option to define uid/gid so if using shared/replicated storage across multiple nodes, it's entirely possible/likely the each node will have different uid/gid and thus will constantly change uid/gid of files/directories on each run.

**Comment by dominics** [comment]
A common way of dealing with this is having a `$manage_user` boolean parameter, and accepting a user/group name as parameters (in case they're managed externally).

This lets users with complicated user provisioning logic (like needing to keep static/shared UID/GIDs for e.g. NFS) manage their user resource outside of this module.
