### ISSUE TITLE
Accepting terms of service

### ISSUE THREAD

**Issue by daemondazz** [bzed/bzed-letsencrypt#29]
Having issues getting dehydrated to accept terms of service:

```
Exec[create-certificate-server.example.net]/returns: # INFO: Using main config file /opt/letsencrypt/letsencrypt.conf
Exec[create-certificate-server.example.net]/returns: To use dehydrated with this certificate authority you have to agree to their terms of service which you can find here: https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
```

Running ```/opt/letsencrypt/dehydrated/dehydrated --register --accept-terms``` generates a new account key in /opt/letsencrypt/dehydrated/accounts and not /opt/letsencrypt/accounts.

Running ```/opt/letsencrypt/dehydrated/dehydrated --register --accept-terms -f /opt/letsencrypt/letsencrypt.conf``` seems to work:

```
# INFO: Using main config file /opt/letsencrypt/letsencrypt.conf
+ Generating account key...
+ Registering account key with ACME server...
+ Done!
```

But now the puppet run complains about an invalid account key:

```
Exec[create-certificate-server.example.net]/returns: # INFO: Using main config file /opt/letsencrypt/letsencrypt.conf
Exec[create-certificate-server.example.net]/returns: ERROR: Account key is not valid, can not continue.
```

Host: Ubuntu 16.04 64 bit
Puppet Server: 2.7.2-1puppetlabs1
PuppetDB: 4.3.0-1puppetlabs1

**Comment by daemondazz** [comment]
Solved the issue, turns out it was a permission issue. Set the ownership of the account directory to letsencrypt and it started working.

**Comment by abozhinov** [comment]
@daemondazz to which folder you set ownership. I have the same problem.

2019/02/24 09:46:35 [error] 25#25: *87 [lua] lets_encrypt.lua:41: issue_cert(): auto-ssl: dehydrated failed: env HOOK_SECRET=XXXXXXXXXXXXXXXXXXX HOOK_SERVER_PORT=8999 /opt/openresty/luajit/bin/resty-auto-ssl/dehydrated --cron --accept-terms --no-lock --domain copy.bg --challenge http-01 --config /etc/resty-auto-ssl/letsencrypt/config --hook /opt/openresty/luajit/bin/resty-auto-ssl/letsencrypt_hooks status: 256 out: # INFO: Using main config file /etc/resty-auto-ssl/letsencrypt/config
 err: ERROR: Account key is not valid, cannot continue.
, context: ssl_certificate_by_lua*, client: 54.36.148.122, server: 0.0.0.0:443
