### ISSUE TITLE
SAN Certificates

### ISSUE THREAD

**Issue by sahal** [bzed/bzed-letsencrypt#3]
Hello,

Letsencrypt.sh [1] as well as the official Let's Encrypt [2] client both support SAN certs. 

Is it possible to request a SAN cert using this puppet module?

1: https://github.com/lukas2511/letsencrypt.sh/blob/master/domains.txt.example
2: https://community.letsencrypt.org/t/frequently-asked-questions-faq/26

**Comment by bzed** [comment]
Hi @sahal!

Sorry, but right now it is not possible to request SAN certificates. It should not be hard to implement, though. I'd happily accept patches ;-) Or you'll have to wait until I find the time to implement it.

Best regards,

Bernd

**Comment by bzed** [comment]
@sahal almost done... just testing it and I guess I'll push the changes tomorrow.
