### ISSUE TITLE
New setups require manual accepting of terms on puppetserver

### ISSUE THREAD

**Issue by mrunkel** [bzed/bzed-letsencrypt#34]
Hi,

First off, thanks for this module.  It's awesome!  However, it was a bit of a head scratcher to get working initially, mainly because the following step isn't documented/automated.

Before dehydrated can request certs, you need to accept the terms and conditions.

I was able to do this manually by:

```
su - letsencrypt
/opt/letsencrypt/dehydrated/dehydrated --register --accept-terms -f /opt/letsencrypt//letsencrypt.conf
```

I'm wondering if this isn't something that can be automated in the manifest?

Or am I missing something else?

**Comment by mrunkel** [comment]
I was able to solve this outside the module with the following exec resource:

```
  exec {'accept-terms':
    user    => 'letsencrypt',
    command => '/opt/letsencrypt/dehydrated/dehydrated --register --accept-terms -f /opt/letsencrypt//letsencrypt.conf',
    creates => '/opt/letsencrypt/accounts',
  }
```

**Comment by bzed** [comment]
Please use https://github.com/bzed/bzed-dehydrated/ - it solves this issue and many others.
