### ISSUE TITLE
Errors after upgrading from 0.1.9 to 0.1.14

### ISSUE THREAD

**Issue by janvonde** [bzed/bzed-letsencrypt#4]
I upgraded from version 0.1.9 directly to 0.1.14. since that I have the following error on the puppetmaster:

> Info: Retrieving pluginfacts
> Info: Retrieving plugin
> Info: Loading facts
> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Concat::Fragment[123.example.org_dh] { require => File[/etc/letsencrypt/certs/123.example.org.dh] }, because File[/etc/letsencrypt/certs/123.example.org.dh] doesn't seem to be in the catalog
> Warning: Not using cache on failed catalog
> Error: Could not retrieve catalog; skipping run

The file exists in the filesystem. What can I do to fix the problem?

**Comment by bzed** [comment]
Is your puppetmaster als the host from which you've requested the cert for 123.example.com?

**Comment by janvonde** [comment]
I have the

> letsencrypt::domains:
> - '123.example.org'

setting in the nodes yaml file in hiera and all information are exported via puppetdb to the puppetmaster. The certificates are requested on the puppetmaster and transfered back to the nodes via puppetdb again...

**Comment by bzed** [comment]
As far as I can see thats the concat part in letsencrypt::deploy::crt failing on you. But that should never be executed on the puppetmaster. Its an exported ressource and should run on your node. Does the puppet agent run on your node(s) succeed?

**Comment by janvonde** [comment]
Oh, @bzed I found my bug and fixed it. From a test scenario I still had the letsencrypt::letsencrypt_host: setting set to a wrong server... I removed that and now everything works again. Thanks for your help and for your time!

I am closing this issue.
