### ISSUE TITLE
Use of getvar broken in puppet 6

### ISSUE THREAD

**Issue by optiz0r** [bzed/bzed-letsencrypt#42]
I'm seeing `no CSR from facter for domain x.y.z` since upgrading to 6, despite `facter -p` showing a CSR for `letsencrypt_csr_x.y.z`.

Suspect it's a result of this: https://forge.puppet.com/puppetlabs/stdlib#getvar
The new built-in https://puppet.com/docs/puppet/6.0/function.html#getvar replaces the stdlib one and has different semantics for handling of dots in the key name.

I've not tested this yet (it's late, just reporting this now before I forget), but according to the docs for https://puppet.com/docs/puppet/6.0/function.html#get, this should work:

```
-$csr_content = pick_default(getvar("::letsencrypt_csr_${domain}"), '')
+$csr_content = pick_default(getvar("::letsencrypt_csr_'${domain}'"), '')
```

**Comment by bzed** [comment]
Thanks for the bug report. If you send me a tested pull request I'm happy to merge it.

But - bzed-letsencrypt will be deprecated soon, https://github.com/bzed/bzed-dehydrated is rewritten from scratch, much more flexible and should support puppet 6 just fine. And - although nobody complained yet - the name change was necessary due to the trademarks. Its missing a proper documentation so far, but so far everything seems to work fine. Not well tested, though.

**Comment by optiz0r** [comment]
ok thanks, i'll look at changing the module at a later date, I just want to get this working for now so it can unblock some other work I want to do first. PR is in the system. I'm struggling to get the tests to run locally, so hopefully travis will prove the changes to be OK.

bundle install and bundle exec rake aren't working "out of the box" for me, I get
```
usr/lib64/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:458:in `block in replace_bin_path': can't find executable rake for gem rake (Gem::Exception)
        from /usr/lib64/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:478:in `block in replace_bin_path'
        from /home/ben/.gem/ruby/2.3.0/bin/rake:23:in `<main>'
```

I see it's not installing the modules into a vendor directory, so I suspect incompatibility with other gems in my path. A pattern I've used in other modules to avoid cross-talk is specifying the bundle path in `.bundle/config` to a local directory, e.g. `vendor/bundle`

Although with this I then get the following, so I think there's something amiss with the gem versions in .lock.
```
$ bundle install
# ..
Downloading rspec-mocks-3.8.0 revealed dependencies not in the API or the lockfile (rspec-support (~> 3.8.0), diff-lcs (< 2.0, >= 1.2.0)).
Either installing with `--full-index` or running `bundle update rspec-mocks` should fix the problem.

In Gemfile:
  beaker-rspec was resolved to 6.2.4, which depends on
    serverspec was resolved to 2.41.3, which depends on
      rspec was resolved to 3.8.0, which depends on
        rspec-mocks
$ bundle exec rake test
Could not find rspec-mocks-3.8.0 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by optiz0r** [comment]
I've found another failure case; this does not handle domains containing dashes (either before or after the changes in #43)

**Comment by bzed** [comment]
The tests failed since some time. Not really going to invest time to fix them.
