### ISSUE TITLE
Issues with Puppet Server 2.3.2 and Puppet 4.5

### ISSUE THREAD

**Issue by foosinn** [bzed/bzed-letsencrypt#5]
Hey,

i'm trying to use your module with the latest Puppetserver:

```
$ puppetserver --version
puppetserver version: 2.3.2
$ puppet --version
4.5.0
```

After a two issues with easy fixes (see https://github.com/foosinn/bzed-letsencrypt) im getting this error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::Compiler failed with error NoMethodError: undefined method `downcase' for nil:NilClass on node icinga-gs.unigs.de
```

Configuration for the master:

```
  class { 'letsencrypt' :
    hook_source => 'puppet:///modules/puppetmaster/pdns.sh'
  }
```

Configuration on the client:

```
class { 'letsencrypt': }
ensure_resource('letsencrypt::certificate', "$::fqdn")
```

**Comment by bzed** [comment]
Hi,

good catch with the two parser errors. Could you send me a pull request please? The downcase-issue sounds like you are missing the puppetlabs-stdlib module. Please install it and try again - necesary modules are listed in metadata.json

Thanks,
Bernd

**Comment by foosinn** [comment]
Maybe just some issues with a version? Dependencies are fetched by librarian-puppet.

```
FORGE
  remote: https://forgeapi.puppetlabs.com
  specs:
    bzed-letsencrypt (0.1.14)
      camptocamp-openssl (>= 1.5.1)
      puppetlabs-concat (>= 2.1.0)
      puppetlabs-stdlib (>= 2.2.0)
      puppetlabs-vcsrepo (>= 1.3.2)
    camptocamp-openssl (1.7.1)
      puppetlabs-stdlib (< 5.0.0, >= 2.0.0)
    nanliu-staging (1.0.3)
    puppetlabs-apache (1.10.0)
      puppetlabs-concat (< 3.0.0, >= 1.1.1)
      puppetlabs-stdlib (< 5.0.0, >= 2.4.0)
    puppetlabs-apt (2.2.2)
      puppetlabs-stdlib (< 5.0.0, >= 4.5.0)
    puppetlabs-concat (2.1.0)
      puppetlabs-stdlib (< 5.0.0, >= 3.2.0)
    puppetlabs-firewall (1.8.1)
    puppetlabs-inifile (1.5.0)
    puppetlabs-mysql (3.7.0)
      nanliu-staging (< 2.0.0, >= 1.0.1)
      puppetlabs-stdlib (< 5.0.0, >= 3.2.0)
    puppetlabs-postgresql (4.7.1)
      puppetlabs-apt (< 3.0.0, >= 1.8.0)
      puppetlabs-concat (< 3.0.0, >= 1.1.0)
      puppetlabs-stdlib (~> 4.0)
    puppetlabs-puppetdb (5.1.2)
      puppetlabs-firewall (< 2.0.0, >= 1.1.3)
      puppetlabs-inifile (< 2.0.0, >= 1.1.3)
      puppetlabs-postgresql (< 5.0.0, >= 4.0.0)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.2)
    puppetlabs-stdlib (4.12.0)
    puppetlabs-vcsrepo (1.3.2)
    saz-ssh (2.8.1)
      puppetlabs-concat (>= 1.0.0)
      puppetlabs-stdlib (>= 2.2.1)
    thias-sysctl (1.0.6)
```

**Comment by bzed** [comment]
```
% grep -r downcase manifests lib templates tests
%
```

Actually I don't use the downcase function in the letsencrypt code.... Not sure how I can help you here.

**Comment by foosinn** [comment]
I've also checked for that. I'll do some tests later today to ensure that this is not coming from somewhere else.

**Comment by foosinn** [comment]
It seems like puppetserver does not have a $::puppetmaster. This leads to exporting a resource with a tag that is undef. Puppetdb tries to lowercase the tags, and throws the error.

I guess the easiest fix is validating $letsencrypt_host in letsencrypt::csr, see #7.

**Comment by siliconalchemy** [comment]
I hit this issue in the latest release.  I think I fixed it by changing:
    $letsencrypt_host = $::letsencrypt::letsencrypt_host,
to
    $letsencrypt_host = $::letsencrypt::letsencrypt_real_host,

in letsencrypt::certificate parameters
